<?php
/** @var Template $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Tpay\Magento\Hyva\ViewModel\TpayCards;

/** @var TpayCards $viewModel */
$viewModel = $block->getData('viewModel');
?>

<div x-data="tpayHyvaCheckoutComponentPaymentMethodTpayCardForm"
     data-rsa="<?= $viewModel->getPublicKey() ?>"
     data-message-unsupported-card="<?= $escaper->escapeHtmlAttr(__('Sorry, your credit card type is currently not supported. Please try another payment method.')) ?>"
     data-message-invalid-card="<?= $escaper->escapeHtmlAttr(__('Your credit card number seems to be invalid.')) ?>"
     x-init="tpayHyvaCheckoutCardIsNewCard"
     id="card_payment_form"
     class="tpay-channel-form-wrapper tpay-content-wrapper-class">
    <div id="card_form" x-show="open" @tpay-card-new.window="tpayHyvaCheckoutCardIsNewCard">
        <div id="card_payment" class="tpay-input-wrapper">
            <div class="tpay-col">
                <div class="tpay-row">
                    <div class="tpay-input-wrapper">
                        <div class="tpay-input-credit-card-number">
                            <div class="tpay-input-label"><?= __('Card number') ?></div>
                            <input id="card_number"
                                   pattern="\d*"
                                   autocomplete="cc-number"
                                   x-on:change="tpayHyvaCheckoutCardChangeCC"
                                   x-on:keyup="tpayHyvaCheckoutCardChangeCC"
                                   :value="cc_number"
                                   size="30"
                                   type="tel"
                                   maxlength="23"
                                   placeholder="XXXX XXXX XXXX XXXX"
                                   tabindex="1"
                                   value=""
                                   class="tpay-input-value"
                                   :class="cc_number_valid"
                            />
                            <div class="tpay-card-icon " :class="cc_type"></div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="tpay-col">
                <div class="tpay-row">
                    <div class="tpay-expiration-date-input tpay-input-wrapper">
                        <div class="tpay-input-label">
                            <?= __('Expiration date') ?>
                        </div>
                        <input id="expiry_date"
                               maxlength="9"
                               type="tel"
                               placeholder="01 / 2020"
                               x-on:change="tpayHyvaCheckoutCardChangeExp"
                               x-on:keyup="tpayHyvaCheckoutCardChangeExp"
                               :value="cc_exp"
                               autocomplete="cc-exp"
                               tabindex="2"
                               value=""
                               class="tpay-input-value"
                               :class="cc_exp_valid"
                        />
                    </div>
                    <div class="tpay-cvv-input tpay-input-wrapper">
                        <div class="tpay-input-label tpay-input-cvc"
                             title="<?= __(
                                 'For MasterCard, Visa or Discover, these are the last three digits placed next to the card user signature.'
                             ) ?>"
                        >
                            <?= __('CVC') ?>
                        </div>
                        <input id="cvc"
                               maxlength="3"
                               type="tel"
                               x-on:change="tpayHyvaCheckoutCardChangeCvc"
                               x-on:keyup="tpayHyvaCheckoutCardChangeCvc"
                               :value="cc_ccv"
                               autocomplete="cc-cvc"
                               placeholder="XXX"
                               tabindex="3"
                               value=""
                               class="tpay-input-value"
                               :class="cc_ccv_valid"
                        />
                    </div>
                </div>
            </div>
        </div>
        <p id="info_msg" x-text="message"></p>
        <?php if ($viewModel->canSaveCC()): ?>
            <div class="tpay-amPmCheckbox" id="tpay-card-save-checkbox">
                <input type="checkbox" id="card_save" name="card_save" :value="save"
                       x-on:change="tpayHyvaCheckoutCardChangeSave"/>
                <label for="card_save" class="tpay-info-label" title="<?= __(
                    'Allow to pay faster for next orders. Card data will be stored on secure tpay.com server.'
                ) ?>">
                    <?= __('Save my card') ?>
                </label>
            </div>
        <?php endif ?>
    </div>
</div>
