<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

?>
<script>
function tpayHyvaCheckoutComponentPaymentMethodTpayCard() {
    return Object.assign(
        {
            checkNewCard() {
                window.dispatchEvent(new CustomEvent('tpay-card-new'))
            }
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('tpayHyvaCheckoutComponentPaymentMethodTpayCard', tpayHyvaCheckoutComponentPaymentMethodTpayCard), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>
