<?php
declare(strict_types=1);

/** @var Template $block */
/** @var TpayCard $magewire */

/** @var Escaper $escaper */

use Tpay\Magento\Hyva\Payment\Method\TpayCard;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<div wire:payment-method="Tpay_Magento2">
    <div class="card_insidebg">
        <div  class="card_tpay-panel-inside-content"  x-data="tpayHyvaCheckoutComponentPaymentMethodTpayCard">
            <div id="saved_card_payment" style="visibility: visible" class="tpay-cards-choice">
                <?php if ($magewire->canSaveCC()): ?>
                    <?php foreach ($magewire->getTokens() as $token): ?>
                        <label for="cardN<?= $token['id'] ?>" name="-<?= $token['vendor'] ?>"  class="mb-0 p-0 cursor-pointer">
                            <input wire:model="saved" type="radio" name="savedId" id="cardN<?= $token['id'] ?>" x-on:change="checkNewCard"
                                   value="<?= $token['id'] ?>" <?php if ($magewire->saved == $token['id']): ?> checked <?php endif ?>/>
                            <span class="h-full text-sm">
                                <?= __('Pay with saved card ') ?>
                                <?= $token['cardShortCode'] ?>
                                <div style="display: inline-block; vertical-align: middle;" class="tpay-<?= $token['vendor'] ?>-icon"></div>
                            </span>
                        </label><br/>
                    <?php endforeach ?>
                <?php endif ?>

                <label for="newCard" class="mb-0 p-0 cursor-pointer">
                    <input  wire:model="saved" type="radio" name="savedId" id="newCard" x-on:change="checkNewCard"
                           value="new_card" <?php if ($magewire->saved == "new_card"): ?> checked <?php endif ?> />
                    <span class="h-full text-sm">
                        <?= __('Pay with a new card') ?>
                        <?php if(!empty($magewire->suffix)): ?>
                            ( **** <?= $magewire->suffix ?>
                            <div style="display: inline-block; vertical-align: middle;" class="<?= $magewire->type ?>"></div> )
                        <?php endif ?>
                    </span>
                </label>
            </div>

        </div>
    </div>

    <div class="checkout-agreements-block">
        <div class="TpayRegulations tpay-regulations-offset">
            <input
                    class="cursor-pointer"
                    type="checkbox"
                    checked
                    name="accept_tos"
                    id="accept_tos"
            />
            <label for="accept_tos">
                <span><?= $escaper->escapeHtml(__('By paying, you accept ')) ?></span>
                <a target="_blank" href="<?= $escaper->escapeUrl($magewire->getTerms()) ?>"><?= $escaper->escapeHtml(__('regulations')) ?></a>.<br>
                <span>
                        <?= $escaper->escapeHtml(__(
                                                     'The personal data administrator is Krajowy Integrator Płatności S.A with its registered office in Poznań. '
                                                 ))
                        ?>
                    </span><br>
                <a target="_blank" href="<?= $escaper->escapeUrl($magewire->getRegulations()) ?>"><?= $escaper->escapeHtml(__('Show full content')) ?></a>.
            </label>
        </div>
    </div>
</div>
